version: "3.7"
services:
   frontend:
      build: ./frontend
      ports:
         - "80:80"
      depends_on:
         - backend
   backend:
      build: ./backend
      ports:
         - "8090:8090"
      depends_on:
         - postgres
   postgres:
      image: postgres:12
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: postgres
      ports:
         - "5432:5432"
