version: "3.7"
volumes:
   postgres-data:

services:
   frontend:
      build: ./frontend
      ports:
         - "80:80"
      depends_on:
         - backend
      environment:
         ENV: dev    
   peer_server:
      build: ./backend/peer_server
      ports:
         - "1234:1234"
      depends_on:
         - backend
   backend:
      build: ./backend
      ports:
         - "8090:8090"
      depends_on:
         - postgres
   postgres:
      image: postgres:latest
      ports:
         - "5432:5432"
      restart: always
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: postgres
      volumes:
         - postgres-data:/var/lib/postgresql/data
